# Generated by Django 5.0.1 on 2024-02-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('planned', 'planned'), ('progress', 'progress'), ('completed', 'completed')], max_length=9),
        ),
    ]
